### ISSUE TITLE
Remove Pods from the remote repo 

### ISSUE THREAD

**Issue by MoElnaggar14** [TahaMahmoud/MyWeather#1]
you need to uncomment `Pods` in the `.gitigonre` file and remove Pods/ .

**Comment by MoElnaggar14** [comment]
References: [Remove Pods](https://stackoverflow.com/questions/34230191/added-pod-files-and-pushed-how-to-undo-how-to-use-gitignore-in-xcode-github)

**Comment by TahaMahmoud** [comment]
Thank you for your time, I removed "pods" directory
